# Generated by Django 3.2.8 on 2021-11-14 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confessapp', '0002_confession_dateofpublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='timeofpublish',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
