# Generated by Django 3.2.8 on 2021-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessapp', '0003_confession_timeofpublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
